navigation:
  - title: Inicio
    url: /
  - title: Blog
    url: /blog
  - title: Clases
    url: /info-clases
  - title: Contacto
    url: /contacto/
  - title: About 
    url: /about

markdown: kramdown  # Jekyll usa kramdown por defecto
highlighter: rouge  # Motor de resaltado (viene con Jekyll)